# Generated by Django 4.1.3 on 2023-01-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
