# Generated by Django 4.1.3 on 2023-01-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
