# Generated by Django 4.1.3 on 2023-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_profile_avatar_profile_website_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
