# Generated by Django 4.1.3 on 2023-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seen',
            field=models.BooleanField(null=True),
        ),
    ]
